const D=window.LEAGUE_DATA||{},Y=window.SEASON_2026||{},E=window.MEFFL_ENGINE||{},Q=new URLSearchParams(location.search);
const e=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const CURRENT_WEEK=Math.max(1,Number(Y.week)||1);
const team=m=>(Y.teams||[]).find(t=>t.manager===m),arch=m=>(D.archetypes||[]).find(a=>a.manager===m),rec=m=>(D.records||[]).find(r=>r.manager===m);
function nav(){return `<header class="site-head"><nav class="nav shell"><a class="brand" href="index.html">ME<span>FFL</span></a><div class="navlinks"><a href="weeks.html">Weekly Write-Ups</a><a href="season-2026.html">2026</a><a href="schedule.html">Schedule</a><a href="trophy-case.html">Trophies</a><a href="history.html">History</a><a href="franchises.html">Franchises</a><a href="head-to-head.html">H2H</a><a href="draft-history.html">Draft</a><a href="transactions.html">Moves</a><a href="waiver-wire.html">Waivers</a><a href="keepers.html">Keepers</a><a href="power-rankings.html">Power</a><a href="playoff-odds.html">Odds</a><a href="record-book.html">Records</a><a href="hall-of-shame.html">Shame</a><a href="press-room.html">Press</a></div><details class="mobile-menu"><summary aria-label="Open site menu"><span class="menu-icon">☰</span><span>Menu</span></summary><div class="mobile-menu-links"><a href="weeks.html">Weekly Write-Ups</a><a href="season-2026.html">2026 War Room</a><a href="schedule.html">Schedule</a><a href="trophy-case.html">Trophies</a><a href="history.html">Season History</a><a href="franchises.html">Franchises</a><a href="head-to-head.html">H2H</a><a href="draft-history.html">Draft</a><a href="transactions.html">Moves</a><a href="waiver-wire.html">Waivers</a><a href="keepers.html">Keepers</a><a href="power-rankings.html">Power</a><a href="playoff-odds.html">Odds</a><a href="record-book.html">Records</a><a href="hall-of-shame.html">Shame</a><a href="press-room.html">Press</a></div></details></nav></header>`}
function foot(){return `<footer><div class="shell footer-inner"><div><strong>Miscellaneous Expenditures</strong><p>Bad decisions, good friends, real money and fake grudges.</p></div><div>Updated: ${e(Y.lastUpdated)}</div></div></footer>`}
function hero(t,c=''){return `<section class="page-hero"><div class="shell"><p class="eyebrow">MISCELLANEOUS EXPENDITURES</p><h1>${e(t)}</h1>${c?`<p class="lede">${e(c)}</p>`:''}</div></section>`}
function sec(t,h,i='',ey=''){return `<section class="section"><div class="shell"><div class="section-head"><div>${ey?`<p class="eyebrow dark">${e(ey)}</p>`:''}<h2>${e(t)}</h2></div>${i?`<p class="section-intro">${e(i)}</p>`:''}</div>${h}</div></section>`}
function card(t,b,ey=''){return `<div class="card">${ey?`<p class="eyebrow dark">${e(ey)}</p>`:''}<h3>${e(t)}</h3><p>${b}</p></div>`}
function currentPowerRows(){const p=E.powerMetrics?E.powerMetrics():[];const by=Object.fromEntries((Y.teams||[]).map(t=>[t.team,t]));return p.length?p.map(x=>({...by[x.team],...x})):Y.teams||[]}
function ranks(){return currentPowerRows().map((t,i)=>`<a class="rank-card" href="franchise.html?manager=${encodeURIComponent(t.manager)}"><div class="rank-num">${t.powerRank||i+1}</div><div class="rank-team"><strong>${e(t.team)}</strong><small>${e(t.manager)} · ${t.gp?`${t.w}-${t.l}`:e(t.projection||'Preseason')}</small></div><div class="rank-grade"><strong>${e(t.grade||'—')}</strong><small>${t.powerIndex?`Power ${t.powerIndex.toFixed(1)}`:`Yahoo ${e(t.yahoo||'—')}`}</small></div></a>`).join('')}
const HOME_DRAFT_BOARD=[{"rank":1,"team":"Wheat Hill Slow Blows","manager":"Tommy","grade":"A+","yahoo":"B"},{"rank":2,"team":"SVDBaller","manager":"Harry","grade":"A+","yahoo":"A+"},{"rank":3,"team":"Rise of the Pleasure Machines","manager":"Christopher","grade":"A","yahoo":"C+"},{"rank":4,"team":"SFPAL Junior 49ers","manager":"Tom","grade":"A-","yahoo":"A+"},{"rank":5,"team":"Bogota Booger Boys","manager":"Andrew","grade":"B+","yahoo":"B-"},{"rank":6,"team":"The Great Communicator","manager":"Matt F.","grade":"A-","yahoo":"D"},{"rank":7,"team":"Premature Ejleculators","manager":"Matty B.","grade":"A-","yahoo":"B-"},{"rank":8,"team":"Jelq Me Jeantly","manager":"Owen","grade":"B+","yahoo":"D"},{"rank":9,"team":"The Breeder","manager":"Patrick","grade":"B","yahoo":"D"},{"rank":10,"team":"MCFISH","manager":"Danny","grade":"B","yahoo":"D+"}];
function draftRankCards(){return HOME_DRAFT_BOARD.map(t=>`<a class="rank-card" href="franchise.html?manager=${encodeURIComponent(t.manager)}"><div class="rank-num">${t.rank}</div><div class="rank-team"><strong>${e(t.team)}</strong><small>${e(t.manager)} · Our ${e(t.grade)}</small></div><div class="rank-grade"><strong>${e(t.grade)}</strong><small>Yahoo ${e(t.yahoo)}</small></div></a>`).join('')}
function publishedWeeks(){return Object.entries(Y.weekly||{}).map(([w,d])=>({week:Number(w),...d})).filter(d=>d.writeup&&!/write-up pending/i.test(d.headline||'')&&!/bracket TBD/i.test(d.headline||'')).sort((a,b)=>b.week-a.week)}
function homepageWeeklies(){let p=publishedWeeks();if(!p.length)return '';let latest=p[0],older=p.slice(1,4);let old=older.length?`<div class="home-weekly-recent"><p class="eyebrow dark">RECENT WEEKS</p><div class="home-weekly-recent-grid">${older.map(d=>`<a class="home-weekly-mini" href="week.html?week=${d.week}"><small>WEEK ${d.week}</small><strong>${e(d.headline)}</strong><span>Read the write-up →</span></a>`).join('')}</div></div>`:'';return `<section class="section home-weekly-section"><div class="shell"><div class="section-head"><div><p class="eyebrow dark">FROM THE LEAGUE DESK</p><h2>Latest Weekly Write-Up</h2></div></div><article class="home-weekly-feature"><div class="home-weekly-copy"><div class="home-weekly-meta"><span>WEEK ${latest.week}</span><span>${e((latest.status||'write-up').toUpperCase())}</span></div><h3>${e(latest.headline)}</h3><p>${e(latest.writeup)}</p><div class="home-weekly-actions"><a class="button primary" href="week.html?week=${latest.week}">Open Week ${latest.week}</a><a class="home-archive-link" href="weeks.html">All weekly write-ups →</a></div></div><aside class="home-weekly-side"><p class="eyebrow">GAME OF THE WEEK</p><h4>${e(latest.gameOfWeek||'To be earned')}</h4><p>${e(latest.gotwCopy||'')}</p><div class="home-weekly-side-rule"></div><p class="eyebrow">TOILET WATCH</p><p>${e(latest.toiletWatch||'Pending.')}</p></aside></article>${old}</div></section>`}
function liveBoardSection(week=CURRENT_WEEK){return `<section class="section scoreboard-section"><div class="shell"><div class="scoreboard-banner"><div><p class="eyebrow dark">LIVE SCOREBOARD</p><h2>Week ${week}</h2></div><p>Game states, projections, close-game alerts and upset watch.</p></div>${E.renderScoreboard?E.renderScoreboard(week):''}</div></section>`}
function home(){let h=(D.history||[]).map(x=>card(`${x.year} — ${x.champion}`,`<b>Runner-up:</b> ${e(x.runnerUp)}<br><b>Toilet:</b> ${e(x.toilet)}<br><br>${e(x.headline)}`)).join('');let leader=HOME_DRAFT_BOARD[0];return `<section class="hero"><div class="shell"><p class="eyebrow">2026 SEASON HUB</p><h1>Miscellaneous<br><em style="color:var(--lime);font-weight:400">Expenditures</em></h1><p class="lede">Three completed seasons of bad beats, keeper theft and playoff heartbreak — plus a 2026 title race built to add another chapter.</p><div class="hero-actions"><a class="button primary" href="draft-history.html#grades">Our 2026 Draft Verdict</a><a class="button ghost" href="weeks.html">Weekly Write-Ups</a><a class="button ghost" href="season-2026.html">2026 War Room</a></div></div></section>`+liveBoardSection(1)+sec('The story so far',`<div class="grid3">${h}</div>`,'Records are nice. The real history is who won, who collapsed and who had to sit behind a microphone.','THREE YEARS OF POOR DECISIONS')+homepageWeeklies()+`<section class="section alt preseason-board"><div class="shell"><div class="section-head"><div><p class="eyebrow dark">OUR PRESEASON BOARD</p><h2>Not Yahoo's rankings</h2></div><p class="section-intro">We graded roster construction, keeper value, positional balance, depth and the price paid.</p></div><div class="notice red"><b>Draft winner: ${e(leader.manager)} — ${e(leader.team)} (${e(leader.grade)}).</b> Yahoo gave this roster ${e(leader.yahoo)}. We did not.</div>${draftRankCards()}</div></section>`}
function franchises(){let st=Object.fromEntries((E.currentStandings?E.currentStandings():[]).map(x=>[x.manager,x]));let h=(Y.teams||[]).map(t=>{let a=arch(t.manager),r=rec(t.manager),s=st[t.manager];return `<a class="card" href="franchise.html?manager=${encodeURIComponent(t.manager)}"><p class="eyebrow dark">${e(t.manager)}</p><h3>${e(t.team)}</h3><div class="stat">${e(r?.record||'')}</div><p><b>${e(a?.title||'')}</b><br>${e(a?.body||'')}</p>${s?.gp?`<p class="small">2026: ${s.w}-${s.l} · ${s.pf.toFixed(2)} PF</p>`:''}</a>`}).join('');return hero('Franchise Files','Every current franchise, from rings to Toilets.')+sec('Know your enemy',`<div class="grid2">${h}</div>`,'','THE RECEIPTS')}
function franchise(){let m=Q.get('manager')||'Tommy',t=team(m),a=arch(m),r=rec(m);if(!t)return hero('Franchise not found');let st=(E.currentStandings?E.currentStandings():[]).find(x=>x.manager===m),sim=(E.simulate?E.simulate():[]).find(x=>x.manager===m),str=(E.streaks?E.streaks():{})[m]||'—';return hero(`${m} — ${t.team}`,a?.title||'')+`<section class="section"><div class="shell profile-top"><div class="profile-box"><div class="big-record">${e(r?.record||'')}</div><p>${e(a?.body||'')}</p><div class="mini-stats"><div class="mini-stat"><b>${e(r?.pf||'')}</b><small>Career PF</small></div><div class="mini-stat"><b>${st?.gp?`${st.w}-${st.l}`:e(t.projection)}</b><small>2026 record</small></div><div class="mini-stat"><b>${e(str)}</b><small>Current streak</small></div></div></div><div class="callout"><h3>${e(a?.title||'')}</h3><p>${e(t.outlook)}</p>${sim?`<p><b>${sim.playoff}% playoffs · ${sim.bye}% bye · ${sim.title}% title · ${sim.press}% press risk</b></p>`:''}</div></div></section>`+sec('2026 outlook',`<div class="grid2">${card('The good',e(t.best))}${card('How this goes wrong',e(t.concern))}</div>`)+(sim?sec('Current path',`<div class="grid3">${card('Projected seed',`Average ${sim.avgSeed} · range ${sim.seedLow}–${sim.seedHigh}`)}${card('Remaining schedule',`SOS rank average ${E.remainingSOS(t.team)?.toFixed(1)||'—'}`)}${card('Likely postseason opponent',e(E.likelyOpponent(t.team)))}</div>`,'','LIVE SEASON MATH'):'')}
function archiveGames(){return E.allGames?E.allGames():[]}
function scoredGame(g){return Number.isFinite(g?.scoreA)&&Number.isFinite(g?.scoreB)}
function gameOrder(g){let r=String(g.round||'');let post=r==='Quarterfinal'?15:r==='Semifinal'||r==='Consolation Semifinal'?16:r==='Final'||/Place|Toilet/i.test(r)?17:0;return (Number(g.year)||0)*100+(Number(g.week)||post||0)}
function seriesDetail(a,b){
  const ms=archiveGames().filter(g=>((g.managerA===a&&g.managerB===b)||(g.managerA===b&&g.managerB===a))&&scoredGame(g)).sort((x,y)=>gameOrder(x)-gameOrder(y));
  let wa=0,wb=0;for(const g of ms){if(g.winner===a)wa++;else if(g.winner===b)wb++}
  let streak='—';if(ms.length){const last=ms[ms.length-1].winner;let n=0;for(let i=ms.length-1;i>=0&&ms[i].winner===last;i--)n++;streak=`${last} W${n}`}
  const largest=ms.length?[...ms].sort((x,y)=>Math.abs(y.scoreA-y.scoreB)-Math.abs(x.scoreA-x.scoreB))[0]:null,last=ms.at(-1)||null;
  return {meetings:ms.length,wa,wb,streak,last,largest};
}
function archiveManagers(){return [...new Set([...(Y.teams||[]).map(t=>t.manager),...archiveGames().flatMap(g=>[g.managerA,g.managerB])].filter(Boolean))]}
function archiveCareerRows(){
  const rows={};for(const m of archiveManagers())rows[m]={manager:m,seasons:new Set(),w:0,l:0,pf:0,pa:0,postW:0,postL:0,titles:0,finals:0,toilets:0,best:99};
  for(const g of archiveGames()){if(!scoredGame(g))continue;for(const m of [g.managerA,g.managerB]){if(!rows[m])continue;rows[m].seasons.add(g.year);const won=g.winner===m,pts=won?g.scoreA:g.scoreB,opp=won?g.scoreB:g.scoreA;if(g.stage==='Regular Season'){rows[m].w+=won?1:0;rows[m].l+=won?0:1;rows[m].pf+=pts;rows[m].pa+=opp}else{rows[m].postW+=won?1:0;rows[m].postL+=won?0:1}}
    if(g.stage==='Postseason'){if(g.round==='Final'){rows[g.winner].titles++;rows[g.winner].finals++;rows[g.loser].finals++;rows[g.winner].best=Math.min(rows[g.winner].best,1);rows[g.loser].best=Math.min(rows[g.loser].best,2)}else if(g.round==='3rd Place'){rows[g.winner].best=Math.min(rows[g.winner].best,3);rows[g.loser].best=Math.min(rows[g.loser].best,4)}else if(g.round==='5th Place'){rows[g.winner].best=Math.min(rows[g.winner].best,5);rows[g.loser].best=Math.min(rows[g.loser].best,6)}else if(g.round==='7th Place'){rows[g.winner].best=Math.min(rows[g.winner].best,7);rows[g.loser].best=Math.min(rows[g.loser].best,8)}else if(/9th Place|Toilet/i.test(g.round)){rows[g.winner].best=Math.min(rows[g.winner].best,9);rows[g.loser].best=Math.min(rows[g.loser].best,10);rows[g.loser].toilets++}}
  }
  return Object.values(rows).map(r=>({...r,seasons:r.seasons.size,pct:r.w/(r.w+r.l||1)}));
}
function seasonArchiveStats(year){
  const games=archiveGames().filter(g=>g.year===year),reg=games.filter(g=>g.stage==='Regular Season'&&scoredGame(g)),post=games.filter(g=>g.stage==='Postseason'&&scoredGame(g)),m={};
  for(const g of reg){for(const who of [g.managerA,g.managerB])m[who]??={manager:who,w:0,l:0,pf:0,pa:0};for(const who of [g.managerA,g.managerB]){const won=g.winner===who,pts=won?g.scoreA:g.scoreB,opp=won?g.scoreB:g.scoreA;m[who].w+=won?1:0;m[who].l+=won?0:1;m[who].pf+=pts;m[who].pa+=opp}}
  const standings=Object.values(m).sort((a,b)=>b.w-a.w||b.pf-a.pf);const high=reg.length?[...reg].sort((a,b)=>Math.max(b.scoreA,b.scoreB)-Math.max(a.scoreA,a.scoreB))[0]:null,low=reg.length?[...reg].sort((a,b)=>Math.min(a.scoreA,a.scoreB)-Math.min(b.scoreA,b.scoreB))[0]:null,big=reg.length?[...reg].sort((a,b)=>Math.abs(b.scoreA-b.scoreB)-Math.abs(a.scoreA-a.scoreB))[0]:null,close=reg.length?[...reg].sort((a,b)=>Math.abs(a.scoreA-a.scoreB)-Math.abs(b.scoreA-b.scoreB))[0]:null,combined=reg.length?[...reg].sort((a,b)=>(b.scoreA+b.scoreB)-(a.scoreA+a.scoreB))[0]:null;
  return {games,reg,post,standings,high,low,big,close,combined};
}
function gameReceipt(g){return g&&scoredGame(g)?`${e(g.winner)} ${g.scoreA.toFixed(2)}–${g.scoreB.toFixed(2)} ${e(g.loser)}`:'—'}

function transactions(){
  let rows=(Y.transactionLeaderboard||[]).map(r=>`<tr><td>${e(r[0])}</td><td>${r[1]||'—'}</td><td>${r[2]||'—'}</td><td>${r[3]||'—'}</td><td><b>${r[4]}</b></td></tr>`).join('');
  const tx=Y.waiverWire?.recentTransactions||[];const tape=tx.length?tx.map(x=>`<div class="activity-card"><div><span class="activity-type">${e(x.type||'MOVE')}</span><strong>${e(x.manager||x.team||'')}</strong></div><p>${e(x.description||[x.add&&`Added ${x.add}`,x.drop&&`Dropped ${x.drop}`].filter(Boolean).join(' · ')||'Completed transaction')}</p><small>${e(x.time||x.date||'')}</small></div>`).join(''):`<div class="empty-state"><b>No 2026 transactions yet.</b><br>The live tape is ready; completed adds, drops, claims and trades will appear here when the season starts.</div>`;
  return hero('Moves & Trades','Some managers build through the draft. Owen rebuilds the plane while it is in the air.')+sec('2026 activity tape',`<div class="activity-feed">${tape}</div><div style="margin-top:18px"><a class="button primary" href="waiver-wire.html">Open Waiver Wire →</a></div>`,'Completed 2026 transactions will populate here alongside the historical move totals.','LIVE SEASON')+sec('Career move leaderboard',`<div class="table-wrap" tabindex="0"><table><thead><tr><th>Manager</th><th>2023</th><th>2024</th><th>2025</th><th>Total</th></tr></thead><tbody>${rows}</tbody></table></div>`,'','THE CHURN')
}
function waiverBody(w){
 const faab=(w.faab||[]).sort((a,b)=>a.priority-b.priority).map(x=>`<tr><td><b>${e(x.priority)}</b></td><td>${e(x.manager)}</td><td>${e(x.team)}</td><td>$${e(x.spent)}</td><td><b>$${e(x.remaining)}</b></td><td>${e(x.claimsWon)}</td></tr>`).join('');
 const avail=(w.topAvailable||[]).length?(w.topAvailable||[]).map((p,i)=>`<tr><td><b>${i+1}</b></td><td>${e(p.name)}</td><td>${e(p.position||'')}</td><td>${e(p.nflTeam||'')}</td><td>${e(p.status||'FA')}</td><td>${e(p.recent||'—')}</td><td>${p.faabSuggestion?e(p.faabSuggestion):'—'}</td></tr>`).join(''):`<tr><td colspan="7"><div class="empty-state"><b>Yahoo connect pending.</b><br>Available players will populate here when live league data is connected.</div></td></tr>`;
 const tx=(w.recentTransactions||[]).length?(w.recentTransactions||[]).map(x=>`<div class="activity-card"><div><span class="activity-type">${e(x.type||'MOVE')}</span><strong>${e(x.manager||x.team||'')}</strong></div><p>${e(x.description||'')}</p><small>${e(x.time||'')}</small></div>`).join(''):`<div class="empty-state"><b>No 2026 transactions yet.</b><br>Completed adds, drops, claims and trades will land here as the season moves.</div>`;
 return `<div class="live-status"><span class="status-dot ${w.apiStatus&&w.apiStatus.toLowerCase().includes('connected')?'on':'off'}"></span><div><b>${e(w.apiStatus&&/connected/i.test(w.apiStatus)?w.apiStatus:'Yahoo connect pending')}</b><small>Last update: ${e(w.lastUpdated||Y.lastUpdated)}</small></div></div><div class="waiver-grid">${card('FAAB season','$100 per team. Spend wisely or become somebody else’s waiver story.','THE BUDGET')}${card('Privacy rule','Completed waiver activity and FAAB spent can be public. Pending bids stay private.','NO CHEATING')}</div><div class="waiver-section"><div class="section-head"><div><p class="eyebrow dark">MONEY LEFT TO BURN</p><h2>FAAB & Waiver Priority</h2></div><p class="section-intro">Everybody begins 2026 with $100 FAAB.</p></div><div class="table-wrap" tabindex="0"><table><thead><tr><th>Priority</th><th>Manager</th><th>Team</th><th>Spent</th><th>Remaining</th><th>Claims Won</th></tr></thead><tbody>${faab}</tbody></table></div></div><div class="waiver-section"><div class="section-head"><div><p class="eyebrow dark">WHO IS STILL OUT THERE?</p><h2>Top Available Players</h2></div></div><div class="table-wrap" tabindex="0"><table><thead><tr><th>#</th><th>Player</th><th>Pos</th><th>NFL</th><th>Status</th><th>Recent</th><th>Suggested FAAB</th></tr></thead><tbody>${avail}</tbody></table></div></div><div class="waiver-section"><div class="section-head"><div><p class="eyebrow dark">THE TAPE</p><h2>League Activity</h2></div><p class="section-intro">Completed moves only.</p></div><div class="activity-feed">${tx}</div></div><p class="yahoo-attribution">Fantasy data provided by Yahoo Fantasy when connected.</p>`;
}
function waivers(){return hero('Waiver Wire','Free agents, FAAB and the transaction tape.')+`<section class="section"><div class="shell"><div id="waiver-live-content">${waiverBody(Y.waiverWire||{})}</div></div></section>`}
async function refreshWaivers(){const cfg=window.MEFFL_API||{},url=cfg.waiverEndpoint;if(!url)return;try{const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);const data=await r.json();data.apiStatus=data.apiStatus||'Connected to Yahoo';data.lastUpdated=data.lastUpdated||new Date().toLocaleString();const el=document.getElementById('waiver-live-content');if(el)el.innerHTML=waiverBody(data)}catch(err){const el=document.querySelector('.live-status b');if(el)el.textContent='Yahoo connection temporarily unavailable'}}
function power(){const p=currentPowerRows();let board=p.map((t,i)=>`<a class="rank-card" href="franchise.html?manager=${encodeURIComponent(t.manager)}"><div class="rank-num">${t.powerRank||i+1}</div><div class="rank-team"><strong>${e(t.team)}</strong><small>${e(t.manager)} · ${t.gp?`${t.w}-${t.l} · ${t.pf.toFixed(2)} PF`:e(t.projection)}</small></div><div class="rank-grade"><strong>${t.powerIndex?t.powerIndex.toFixed(1):e(t.grade)}</strong><small>${t.gp?'Power index':`Yahoo ${e(t.yahoo)}`}</small></div></a>`).join('');return hero('Weekly Power Rankings','The page where confidence goes to die one Sunday at a time.')+sec(`Week ${CURRENT_WEEK} snapshot`,board,'Preseason roster strength gradually gives way to record and scoring as games are completed.','THE CURRENT PECKING ORDER')}
function simRows(){return [...(E.simulate?E.simulate():[])].sort((a,b)=>b.playoff-a.playoff)}
function barsModel(field,red=false){return simRows().map(x=>`<div class="odds-row"><strong>${e(x.team)}<span class="table-sub">${e(x.manager)}</span></strong><div class="bar${red?' red':''}"><span style="width:${Math.min(100,x[field])}%"></span></div><b>${x[field]}%</b></div>`).join('')}
function odds(){let o=simRows();let st=Object.fromEntries((E.currentStandings?E.currentStandings():[]).map(x=>[x.team,x]));let rows=o.map((x,i)=>`<tr><td>${i+1}</td><td><b>${e(x.team)}</b><div class="table-sub">${e(x.manager)}</div></td><td>${st[x.team]?.gp?`${st[x.team].w}-${st[x.team].l}`:'0-0'}</td><td><b>${x.playoff}%</b></td><td>${x.bye}%</td><td>${x.title}%</td><td>${e(x.avgSeed)}</td><td>${x.seedLow}–${x.seedHigh}</td><td>${x.press}%</td></tr>`).join('');return hero('Playoff Odds','Live league math for the bracket, first-round byes, title equity and the odds of meeting the microphones.')+sec('Make the bracket',barsModel('playoff'),'Top six qualify.','PLAYOFF PROBABILITY')+sec('Earn a first-round bye',barsModel('bye'),'Only the top two regular-season seeds get the week off.','TOP-TWO EQUITY')+sec('Win the whole damn thing',barsModel('title'),'Team strength carries through the six-team title bracket.','TITLE EQUITY')+sec('Press-conference risk',barsModel('press',true),'The bottom-four path ends with a 9th-place game nobody wants to lose.','THE BAD ODDS')+sec('Full model board',`<div class="table-wrap" tabindex="0"><table><thead><tr><th>#</th><th>Team</th><th>Record</th><th>Playoffs</th><th>Bye</th><th>Title</th><th>Avg seed</th><th>Seed range</th><th>Press risk</th></tr></thead><tbody>${rows}</tbody></table></div>`,'The model updates when real results are added.','THE NUMBERS')}
function records(){
  const book=E.recordWatch?E.recordWatch():(Y.recordBook||[]).map(r=>({record:r[0],holder:r[1],number:r[2],receipt:r[3]}));let rows=book.map(r=>`<tr><td>${e(r.record)}</td><td>${e(r.holder)}</td><td><b>${e(r.number)}</b></td><td>${e(r.receipt)}</td></tr>`).join('');
  const reg=archiveGames().filter(g=>g.stage==='Regular Season'&&scoredGame(g));
  const hi=[...reg].sort((a,b)=>Math.max(b.scoreA,b.scoreB)-Math.max(a.scoreA,a.scoreB))[0],lo=[...reg].sort((a,b)=>Math.min(a.scoreA,a.scoreB)-Math.min(b.scoreA,b.scoreB))[0],big=[...reg].sort((a,b)=>Math.abs(b.scoreA-b.scoreB)-Math.abs(a.scoreA-a.scoreB))[0],close=[...reg].sort((a,b)=>Math.abs(a.scoreA-a.scoreB)-Math.abs(b.scoreA-b.scoreB))[0],comb=[...reg].sort((a,b)=>(b.scoreA+b.scoreB)-(a.scoreA+a.scoreB))[0];
  const single=(g,which)=>{if(!g)return '—';if(which==='high')return `${g.winner} — ${g.scoreA.toFixed(2)} (${g.year} W${g.week})`;if(which==='low')return `${g.loser} — ${g.scoreB.toFixed(2)} (${g.year} W${g.week})`;return gameReceipt(g)};
  const career=archiveCareerRows().sort((a,b)=>b.w-a.w||b.pf-a.pf).map((r,i)=>`<tr><td>${i+1}</td><td><b>${e(r.manager)}</b></td><td>${r.seasons}</td><td>${r.w}-${r.l}</td><td>${(r.pct*100).toFixed(1)}%</td><td>${r.pf.toFixed(2)}</td><td>${r.pa.toFixed(2)}</td><td>${r.postW}-${r.postL}</td><td>${r.titles}</td><td>${r.finals}</td><td>${r.toilets}</td></tr>`).join('');
  const streaks={};for(const m of archiveManagers()){const gs=reg.filter(g=>g.managerA===m||g.managerB===m).sort((a,b)=>gameOrder(a)-gameOrder(b));let cw=0,cl=0,mw=0,ml=0;for(const g of gs){if(g.winner===m){cw++;cl=0;mw=Math.max(mw,cw)}else{cl++;cw=0;ml=Math.max(ml,cl)}}streaks[m]={mw,ml}}
  const winSt=Object.entries(streaks).sort((a,b)=>b[1].mw-a[1].mw)[0],lossSt=Object.entries(streaks).sort((a,b)=>b[1].ml-a[1].ml)[0];
  return hero('Record Book','The numbers nobody is allowed to forget.')+sec('League records',`<div class="table-wrap" tabindex="0"><table><thead><tr><th>Record</th><th>Holder</th><th>Number</th><th>Receipt</th></tr></thead><tbody>${rows}</tbody></table></div>`)+sec('Historical scoring vault',`<div class="grid3">${card('Highest regular-season score',single(hi,'high'),'CEILING')}${card('Lowest regular-season score',single(lo,'low'),'FLOOR')}${card('Biggest blowout',`${gameReceipt(big)}<br><span class="small">Margin ${Math.abs(big.scoreA-big.scoreB).toFixed(2)}</span>`,'MERCY RULE')}${card('Closest finish',`${gameReceipt(close)}<br><span class="small">Margin ${Math.abs(close.scoreA-close.scoreB).toFixed(2)}</span>`,'INCHES')}${card('Highest combined score',`${gameReceipt(comb)}<br><span class="small">Combined ${(comb.scoreA+comb.scoreB).toFixed(2)}</span>`,'SHOOTOUT')}${card('Longest streaks',`${e(winSt?.[0])} W${winSt?.[1].mw||0}<br>${e(lossSt?.[0])} L${lossSt?.[1].ml||0}`,'RUNS')}</div>`,'2023–2025 standard-scoring archive; 2026 half-PPR records are tracked separately above.','THE VAULT')+sec('Career standings',`<div class="table-wrap" tabindex="0"><table><thead><tr><th>#</th><th>Manager</th><th>Seasons</th><th>Record</th><th>Win %</th><th>PF</th><th>PA</th><th>Postseason</th><th>Titles</th><th>Finals</th><th>Toilets</th></tr></thead><tbody>${career}</tbody></table></div>`,'Jeremy’s 2023–24 history remains separate from Tom’s 2025/current history.','FULL LEDGER')+sec('League ledger',E.renderLeaderboards?E.renderLeaderboards():'','Career wins, points, postseason appearances, titles and porcelain history.','HISTORICAL LEADERBOARDS')
}
function weeks(){let h='';for(let w=1;w<=17;w++){let d=Y.weekly?.[String(w)]||{},post=w>=15;let status=post?(E.officialRegularSeason&&E.officialRegularSeason()?'BRACKET SET':'PROJECTED BRACKET'):d.status||'scheduled';let headline=post?'Championship + press-conference bracket':d.headline||`Week ${w}`;h+=`<a class="week-card${w===CURRENT_WEEK?' current':''}" href="week.html?week=${w}"><div class="week-status">${e(status)}</div><h3>Week ${w}</h3><p>${e(headline)}</p></a>`}let published=publishedWeeks(),latest=published[0],feature=latest?`<section class="section home-weekly-section"><div class="shell"><div class="section-head"><div><p class="eyebrow dark">FROM THE LEAGUE DESK</p><h2>Week ${latest.week} Write-Up</h2></div><p class="section-intro">The latest published league write-up.</p></div><article class="home-weekly-feature"><div class="home-weekly-copy"><div class="home-weekly-meta"><span>WEEK ${latest.week}</span><span>${e((latest.status||'write-up').toUpperCase())}</span></div><h3>${e(latest.headline)}</h3><p>${e(latest.writeup)}</p><div class="home-weekly-actions"><a class="button primary" href="week.html?week=${latest.week}">Open Week ${latest.week}</a></div></div><aside class="home-weekly-side"><p class="eyebrow">GAME OF THE WEEK</p><h4>${e(latest.gameOfWeek||'To be earned')}</h4><p>${e(latest.gotwCopy||'')}</p><div class="home-weekly-side-rule"></div><p class="eyebrow">TOILET WATCH</p><p>${e(latest.toiletWatch||'Pending.')}</p></aside></article></div></section>`:'';return hero('2026 Weekly Write-Ups')+feature+sec('Every week gets receipts',`<div class="week-grid">${h}</div>`)}
function week(){let w=Number(Q.get('week')||1),d=Y.weekly?.[String(w)]||{};if(w>=15)return hero(`Week ${w} — 2026`,'The bracket takes over.')+sec('Postseason board',E.postseasonBracket?E.postseasonBracket(w):'','Projected before Week 14 is complete; official after the regular season closes.','CHAMPIONSHIP + TOILET PATH');let matchups=d.matchups||[],pro=matchups.map(m=>E.renderMatchupCard?E.renderMatchupCard(m[0],m[1],w):`<div class="matchup"><span>${e(m[0])}</span><span>VS</span><span>${e(m[1])}</span></div>`).join('');let aw=(d.awards||[]).map(a=>card(e(a[1]),'',e(a[0]))).join('')||card('Awards pending','Whatever stupidity the week earns.');let write=`<section class="section"><div class="shell grid2"><div><p class="eyebrow dark">THE WRITE-UP</p><h2>${e(d.headline||`Week ${w}`)}</h2><p class="writeup-copy">${e(d.writeup||'Write-up pending.')}</p></div><div class="gotw"><p class="eyebrow">GAME OF THE WEEK</p><h3>${e(d.gameOfWeek||'To be earned')}</h3><p>${e(d.gotwCopy||'')}</p></div></div></section>`;return hero(`Week ${w} — 2026`,d.headline||'')+(w===1?liveBoardSection(1):'')+write+sec('Matchup room',`<div class="matchup-pro-grid">${pro}</div>`,'All verified historical meetings plus the current season as results arrive.','HISTORY + LEVERAGE')+`<section class="section alt"><div class="shell grid3">${card('Standings movement',e(d.standingsMovement||'Pending.'),'THE TABLE')}${card('Who smells trouble?',e(d.toiletWatch||'Pending.'),'TOILET WATCH')}${card('Quote of the week',e(d.quote||'Pending.'),'FROM THE GROUP CHAT')}</div></section>`+sec('Weekly awards',`<div class="grid3">${aw}</div>`)+`<section class="section dark"><div class="shell"><h2>Power rankings</h2>${ranks()}</div></section>`}
function history(){
  let cards=(D.seasonHistory||D.history||[]).map(s=>{let post=s.year===2026?'The first half-PPR season is open. The bracket will write the rest.':s.postseason||'',btn=s.year<2026?`<div class="season-links"><a class="button small-button" href="season-${s.year}.html">Open ${s.year} season →</a></div>`:'';return `<article class="history-card season-history-card"><div class="history-year">${e(s.year)}</div><div class="season-status ${s.status==='in progress'?'live-season':''}">${s.status==='in progress'?'IN PROGRESS':'FINAL'}</div><h3>${e(s.champion)}</h3><p><b>Runner-up:</b> ${e(s.runnerUp)}</p><p><b>Format:</b> ${e(s.format||'')}</p><p>${e(s.regularSeason||s.headline||'')}</p><div class="history-post"><b>Postseason:</b> ${e(post)}</div><div class="toilet">🚽 ${e(s.toilet)}<small>${e(s.legacy||s.toiletCopy||'')}</small></div>${btn}</article>`}).join('');
  return hero('Season History','Every season gets one permanent chapter: regular-season story, champion, runner-up, postseason damage and the person who had to answer for it.')+sec('The complete timeline',`<div class="history-grid season-history-grid">${cards}</div>`,'2023–2025 are final. 2026 is the first half-PPR season.','THE YEARS')+`<section class="section dark"><div class="shell"><div class="section-head"><div><p class="eyebrow">THE LONG VIEW</p><h2>Three completed seasons, two Tommy banners, one league that learns nothing</h2></div></div><div class="grid3">${card('Championship lineage','Jeremy opened the league with the 2023 title. Tommy answered with back-to-back championships in 2024 and 2025.')}${card('Porcelain lineage','Matt F. → Owen → Matty B. The Hall of Shame has never needed a repeat resident — yet.')}${card('2026 evolution','The league moved from standard scoring to 0.5 PPR, while the keeper constitution and press-conference punishment stayed intact.')}</div></div></section>`
}
function warroom(){
  const keep=(Y.keepers2026||[]).map(k=>`<tr><td>${e(k.manager)}</td><td><b>${e(k.player)}</b></td><td>Round ${e(k.round)}</td></tr>`).join(''),settings=Object.entries(Y.settings2026||{}).map(([k,v])=>card(e(k),e(v))).join('');
  const sim=E.simulate?E.simulate():[],st=Object.fromEntries((E.currentStandings?E.currentStandings():[]).map(x=>[x.team,x])),pow=Object.fromEntries((E.powerMetrics?E.powerMetrics():[]).map(x=>[x.team,x]));
  const race=[...sim].sort((a,b)=>a.avgSeed-b.avgSeed).map((x,i)=>{const c=E.clinchInfo?E.clinchInfo(x.team):{},s=st[x.team],p=pow[x.team];return `<tr><td>${i+1}</td><td><b>${e(x.team)}</b><div class="table-sub">${e(x.manager)}</div></td><td>${s?.gp?`${s.w}-${s.l}`:'0-0'}</td><td>${p?.powerIndex?p.powerIndex.toFixed(1):'—'}</td><td>${E.remainingSOS?E.remainingSOS(x.team).toFixed(2):'—'}</td><td>${x.seedLow}–${x.seedHigh}</td><td>${x.playoff}%</td><td>${x.bye}%</td><td>${x.title}%</td><td>${x.press}%</td><td>${c.playoffMagic??'—'}</td><td>${c.elimination??'—'}</td><td>${e(E.likelyOpponent?E.likelyOpponent(x.team):'—')}</td></tr>`}).join('');
  return hero('2026 War Room','The command center for the first half-PPR season: standings leverage, projected seeds, bracket odds and what every team needs next.')+`<section class="section"><div class="shell"><div class="metric-grid"><div class="metric"><b>10</b><span>teams</span></div><div class="metric"><b>${(Y.keepers2026||[]).length}</b><span>keepers</span></div><div class="metric"><b>$100</b><span>starting FAAB</span></div><div class="metric"><b>0.5</b><span>PPR</span></div><div class="metric"><b>${CURRENT_WEEK}</b><span>current week</span></div></div></div></section>`+liveBoardSection(1)+sec('Race Dashboard',`<div class="table-wrap" tabindex="0"><table><thead><tr><th>Proj.</th><th>Team</th><th>Record</th><th>Power</th><th>ROS SOS</th><th>Seed range</th><th>Playoff</th><th>Bye</th><th>Title</th><th>Press</th><th>Magic</th><th>Elim</th><th>Likely opponent</th></tr></thead><tbody>${race}</tbody></table></div>`,'Every team in one view: leverage, schedule, seed range and postseason path.','THE RACE')+sec('What everybody needs',E.renderWarRoomIntel?E.renderWarRoomIntel():'','Magic numbers, elimination pressure, remaining schedule, projected seed range and likely opponent.','THE WAR BOARD')+sec('Keeper arsenal',`<div class="table-wrap" tabindex="0"><table><thead><tr><th>Manager</th><th>Keeper</th><th>2026 cost</th></tr></thead><tbody>${keep}</tbody></table></div>`,'','KEEPER VALUE')+sec('League setup',`<div class="grid3">${settings}</div>`,'The rules most likely to matter once people start losing.','THE CONSTITUTION')
}
function h2h(){
  const all=archiveGames(),managers=archiveManagers(),pairs=[];
  for(let i=0;i<managers.length;i++)for(let j=i+1;j<managers.length;j++){const x=E.series?E.series(managers[i],managers[j]):{total:0};if(x.total){const d=seriesDetail(managers[i],managers[j]);pairs.push({a:managers[i],b:managers[j],...x,...d})}}
  pairs.sort((a,b)=>b.total-a.total||a.a.localeCompare(b.a));
  const rows=pairs.map(x=>`<tr><td>${e(x.a)}</td><td><b>${x.w}-${x.l}</b></td><td>${e(x.b)}</td><td>${x.regW}-${x.regL}</td><td>${x.postW}-${x.postL}</td><td>${x.total}</td><td>${e(x.streak)}</td><td>${x.last?gameReceipt(x.last):'—'}</td><td>${x.largest?`${e(x.largest.winner)} +${Math.abs(x.largest.scoreA-x.largest.scoreB).toFixed(2)}`:'—'}</td></tr>`).join('');
  const most=pairs[0],closest=[...pairs].filter(x=>x.total>=4).sort((a,b)=>Math.abs(a.wa-a.wb)-Math.abs(b.wa-b.wb)||b.total-a.total)[0],lopsided=[...pairs].sort((a,b)=>Math.abs(b.wa-b.wb)-Math.abs(a.wa-a.wb)||b.total-a.total)[0];
  const biggest=[...all].filter(scoredGame).sort((a,b)=>Math.abs(b.scoreA-b.scoreB)-Math.abs(a.scoreA-a.scoreB))[0];
  const games=[...all].sort((a,b)=>gameOrder(b)-gameOrder(a)).map(g=>`<tr><td>${g.year}</td><td>${e(g.round)}</td><td>${e(g.stage)}</td><td class="win">${e(g.winner||'—')}</td><td>${scoredGame(g)?`${g.scoreA.toFixed(2)}–${g.scoreB.toFixed(2)}`:'—'}</td><td class="loss">${e(g.loser||'—')}</td></tr>`).join('');
  return hero('Head-to-Head','Every verified regular-season and postseason meeting from 2023 through today.')+sec('Rivalry superlatives',`<div class="grid4">${card('Most meetings',most?`${e(most.a)} vs ${e(most.b)}<br><span class="small">${most.total} games · ${most.wa}-${most.wb}</span>`:'—','FAMILIAR FOES')}${card('Closest series',closest?`${e(closest.a)} ${closest.wa}-${closest.wb} ${e(closest.b)}<br><span class="small">${closest.total} meetings</span>`:'—','DEAD EVEN')}${card('Most lopsided series',lopsided?`${e(lopsided.a)} ${lopsided.wa}-${lopsided.wb} ${e(lopsided.b)}`:'—','OWNERSHIP')}${card('Largest victory',biggest?`${gameReceipt(biggest)}<br><span class="small">Margin ${Math.abs(biggest.scoreA-biggest.scoreB).toFixed(2)}</span>`:'—','BEATDOWN')}</div>`,'','RIVALRY RECORDS')+sec('Rivalry room',`<div class="notice"><b>Full archive:</b> 210 regular-season games from 2023–2025 plus 31 postseason/consolation games are included. Jeremy’s 2023–24 history remains separate from Tom’s 2025 franchise history.</div><div class="table-wrap" tabindex="0"><table><thead><tr><th>Manager A</th><th>Overall</th><th>Manager B</th><th>Regular</th><th>Post</th><th>Meetings</th><th>Series streak</th><th>Previous meeting</th><th>Largest win</th></tr></thead><tbody>${rows}</tbody></table></div>`,'Exact previous meetings, series streaks and largest margins come from the complete archive.','FULL H2H')+sec('Every receipt',`<div class="table-wrap" tabindex="0"><table><thead><tr><th>Season</th><th>Week / Round</th><th>Stage</th><th>Winner</th><th>Score</th><th>Loser</th></tr></thead><tbody>${games}</tbody></table></div>`,'','241-GAME ARCHIVE')
}
function seasonArchive(){
  const year=Number(document.body.dataset.year||Q.get('year')||2023),z=seasonArchiveStats(year),meta=(D.seasonHistory||[]).find(x=>Number(x.year)===year)||{};
  const standings=z.standings.map((r,i)=>`<tr><td>${i+1}</td><td><b>${e(r.manager)}</b></td><td>${r.w}-${r.l}</td><td>${(100*r.w/(r.w+r.l||1)).toFixed(1)}%</td><td>${r.pf.toFixed(2)}</td><td>${r.pa.toFixed(2)}</td></tr>`).join('');
  const post=z.post.map(g=>`<tr><td>${e(g.round)}</td><td><b>${e(g.winner)}</b></td><td>${g.scoreA.toFixed(2)}–${g.scoreB.toFixed(2)}</td><td>${e(g.loser)}</td></tr>`).join('');
  const weeks=Array.from({length:14},(_,i)=>i+1).map(w=>`<article class="season-week-card"><div class="schedule-week-head"><span>WEEK ${w}</span></div>${z.reg.filter(g=>g.week===w).map(g=>`<div class="season-receipt"><b>${e(g.winner)}</b><span>${g.scoreA.toFixed(2)}–${g.scoreB.toFixed(2)}</span><b>${e(g.loser)}</b></div>`).join('')}</article>`).join('');
  return hero(`${year} Season`,meta.format||'10 teams · standard scoring')+`<section class="section"><div class="shell"><div class="metric-grid"><div class="metric"><b>${e(String(meta.champion||'').split(' — ')[0]||'—')}</b><span>champion</span></div><div class="metric"><b>${e(String(meta.runnerUp||'').split(' — ')[0]||'—')}</b><span>runner-up</span></div><div class="metric"><b>${e(String(meta.toilet||'').split(' — ')[0]||'—')}</b><span>toilet</span></div><div class="metric"><b>${z.reg.length}</b><span>regular games</span></div><div class="metric"><b>${z.post.length}</b><span>postseason games</span></div></div><div class="season-year-nav"><a href="season-2023.html">2023</a><a href="season-2024.html">2024</a><a href="season-2025.html">2025</a></div></div></section>`+sec('Final regular-season standings',`<div class="table-wrap" tabindex="0"><table><thead><tr><th>#</th><th>Manager</th><th>Record</th><th>Win %</th><th>PF</th><th>PA</th></tr></thead><tbody>${standings}</tbody></table></div>`,meta.regularSeason||'','THE TABLE')+sec('Season scoring notables',`<div class="grid3">${card('Highest score',z.high?`${z.high.winner} — ${z.high.scoreA.toFixed(2)} · W${z.high.week}`:'—')}${card('Lowest score',z.low?`${z.low.loser} — ${z.low.scoreB.toFixed(2)} · W${z.low.week}`:'—')}${card('Biggest margin',z.big?`${gameReceipt(z.big)}<br><span class="small">+${Math.abs(z.big.scoreA-z.big.scoreB).toFixed(2)}</span>`:'—')}${card('Closest game',z.close?`${gameReceipt(z.close)}<br><span class="small">${Math.abs(z.close.scoreA-z.close.scoreB).toFixed(2)} points</span>`:'—')}${card('Highest combined',z.combined?`${gameReceipt(z.combined)}<br><span class="small">${(z.combined.scoreA+z.combined.scoreB).toFixed(2)} combined</span>`:'—')}${card('Postseason legacy',e(meta.postseason||''))}</div>`,'','SEASON VAULT')+sec('Full postseason',`<div class="table-wrap" tabindex="0"><table><thead><tr><th>Round</th><th>Winner</th><th>Score</th><th>Loser</th></tr></thead><tbody>${post}</tbody></table></div>`,meta.legacy||'','THE BRACKET')+sec('Week-by-week receipts',`<div class="schedule-week-grid">${weeks}</div>`,'All 70 regular-season games, preserved exactly.','THE REGULAR SEASON')
}
function trophies(){
  const r=archiveCareerRows().sort((a,b)=>b.titles-a.titles||b.finals-a.finals||a.best-b.best||b.w-a.w),rows=r.map((x,i)=>`<tr><td>${i+1}</td><td><b>${e(x.manager)}</b></td><td>${x.titles}</td><td>${x.finals}</td><td>${x.best<99?`${x.best}${x.best===1?'st':x.best===2?'nd':x.best===3?'rd':'th'}`:'—'}</td><td>${x.w}-${x.l}</td><td>${x.postW}-${x.postL}</td><td>${x.toilets}</td></tr>`).join('');
  return hero('Trophy Case','Hardware, heartbreak and the titles nobody wants.')+sec('Championship banners',`<div class="banner-row"><div class="banner"><small>League Champion</small><div class="yr">2023</div><strong>Jeremy — Bye Week</strong></div><div class="banner"><small>League Champion</small><div class="yr">2024</div><strong>Tommy — Chubb And Tug</strong></div><div class="banner"><small>League Champion</small><div class="yr">2025</div><strong>Tommy — Back-to-Back Champion</strong></div></div>`,'One Jeremy banner. Two Tommy banners. Everybody else has a story.','THE CEILING OF ENVY')+sec('Title leaderboard',`<div class="table-wrap" tabindex="0"><table><thead><tr><th>#</th><th>Manager</th><th>Titles</th><th>Finals</th><th>Best finish</th><th>Career record</th><th>Postseason / placement</th><th>Toilets</th></tr></thead><tbody>${rows}</tbody></table></div>`,'Every manager in the archived era, including zero-title and zero-finals histories.','THE HARDWARE LEDGER')+sec('The other kind of champion',`<div class="grid3"><div class="press-card"><h3>🚽 2023 — Matt F.</h3><p>The inaugural porcelain resident.</p></div><div class="press-card"><h3>🚽 2024 — Owen</h3><p>72 moves and one microphone.</p></div><div class="press-card"><h3>🚽 2025 — Matty B.</h3><p>Two straight 2-12 seasons finally reached the podium.</p></div></div>`,'There are two ways to become immortal in this league. This is the worse one.','PORCELAIN LEGACY')
}

function schedule(){
  const sched=E.schedule2026?E.schedule2026():{}, teams=Y.teams||[], rank=Object.fromEntries(HOME_DRAFT_BOARD.map(t=>[t.team,Number(t.rank)||99])), mgr=t=>E.managerByTeam?E.managerByTeam(t):t;
  const games=[];for(let w=1;w<=14;w++)for(const [a,b] of (sched[String(w)]||[]))games.push({w,a,b,ma:mgr(a),mb:mgr(b)});
  const key=(a,b)=>[a,b].sort().join('|'), finalTags={}; finalTags[key('Tommy','Christopher')]='2024 FINAL REMATCH'; finalTags[key('Tommy','Matt F.')]='2025 FINAL REMATCH';
  const pairWeeks={};for(const g of games)(pairWeeks[key(g.ma,g.mb)]??=[]).push(g.w);
  const reg=(ma,mb)=>{const z=E.series?E.series(ma,mb):{regW:0,regL:0};return {w:z.regW||0,l:z.regL||0,total:(z.regW||0)+(z.regL||0)}};
  const tags=g=>{const z=[],k=key(g.ma,g.mb),r=reg(g.ma,g.mb);if(finalTags[k])z.push(finalTags[k]);if((rank[g.a]||99)<=4&&(rank[g.b]||99)<=4)z.push('TOP-4 CLASH');if(r.total>=5&&Math.abs(r.w-r.l)<=1)z.push('RIVALRY');if((pairWeeks[k]||[]).length>1&&g.w>Math.min(...pairWeeks[k]))z.push('SEASON REMATCH');return z};
  const roads=teams.map(t=>{const rs=[];for(let w=1;w<=14;w++){const g=(sched[String(w)]||[]).find(x=>x.includes(t.team));if(g){const o=g[0]===t.team?g[1]:g[0];rs.push(rank[o]||10)}}return {...t,avg:rs.reduce((a,b)=>a+b,0)/(rs.length||1)}}).sort((a,b)=>a.avg-b.avg);
  const uniq=[...new Map(games.map(g=>[key(g.ma,g.mb),g])).values()];
  const familiar=[...uniq].sort((a,b)=>reg(b.ma,b.mb).total-reg(a.ma,a.mb).total)[0];
  const wk1=[...games.filter(g=>g.w===1)].sort((a,b)=>(rank[a.a]+rank[a.b])-(rank[b.a]+rank[b.b]))[0];
  const closest=[...uniq].filter(g=>reg(g.ma,g.mb).total>=4).sort((a,b)=>Math.abs(reg(a.ma,a.mb).w-reg(a.ma,a.mb).l)-Math.abs(reg(b.ma,b.mb).w-reg(b.ma,b.mb).l)||reg(b.ma,b.mb).total-reg(a.ma,a.mb).total)[0];
  const marquee=[...games].filter(g=>tags(g).length).sort((a,b)=>{const sc=g=>tags(g).reduce((s,t)=>s+(t.includes('FINAL REMATCH')?100:t==='TOP-4 CLASH'?35:t==='RIVALRY'?25:10),0);return sc(b)-sc(a)||a.w-b.w}).slice(0,16).map(g=>{const r=reg(g.ma,g.mb);return `<a class="marquee-game" href="week.html?week=${g.w}"><div><span>WEEK ${g.w}</span><b>${e(g.a)} vs ${e(g.b)}</b><small>${e(g.ma)} ${r.w}-${r.l} ${e(g.mb)} in 2023–25 regular-season meetings</small></div><div>${tags(g).map(x=>`<em>${e(x)}</em>`).join('')}</div></a>`}).join('');
  const teamCards=teams.map(t=>{const lines=[];for(let w=1;w<=14;w++){const g=(sched[String(w)]||[]).find(x=>x.includes(t.team));if(!g)continue;const o=g[0]===t.team?g[1]:g[0],om=mgr(o),r=reg(t.manager,om),h=E.matchupHistory?E.matchupHistory(t.team,o):null,tg=tags({w,a:t.team,b:o,ma:t.manager,mb:om});lines.push(`<a class="schedule-line${tg.length?' big':''}" href="week.html?week=${w}"><span class="schedule-week">W${w}</span><span class="schedule-opponent">${E.badge?E.badge(o,'xs'):''}<b>${e(o)}</b><small>${e(om)} · REG H2H ${e(t.manager)} ${r.w}-${r.l}</small><small class="schedule-last">${h&&h.total?`Last: ${e(h.previous)}`:'First meeting in the archive'}</small></span><span class="schedule-tags">${tg.map(x=>`<em>${e(x)}</em>`).join('')}</span></a>`)}return `<article class="schedule-team-card"><div class="schedule-team-head"><div><p class="eyebrow dark">PRESEASON #${e(rank[t.team]||t.rank)}</p><h3>${e(t.team)}</h3><p>${e(t.manager)} · Avg opponent preseason rank ${roads.find(x=>x.team===t.team).avg.toFixed(2)}</p></div></div>${lines.join('')}</article>`}).join('');
  const weekly=Array.from({length:14},(_,i)=>i+1).map(w=>`<article class="schedule-week-card"><div class="schedule-week-head"><span>WEEK ${w}</span><a href="week.html?week=${w}">Open week →</a></div>${(sched[String(w)]||[]).map(([a,b])=>{const ma=mgr(a),mb=mgr(b),r=reg(ma,mb),tg=tags({w,a,b,ma,mb});return `<div class="schedule-master-game"><div><b>${e(a)}</b><span>vs</span><b>${e(b)}</b></div><small>${e(ma)} ${r.w}-${r.l} ${e(mb)}</small><div>${tg.map(x=>`<em>${e(x)}</em>`).join('')}</div></div>`}).join('')}</article>`).join('');
  return hero('2026 Schedule','Fourteen regular-season weeks with the full 2023–2025 receipts attached.')+`<section class="section"><div class="shell"><div class="section-head"><div><p class="eyebrow dark">SCHEDULE NOTABLES</p><h2>What jumps off the page</h2></div><p class="section-intro">Difficulty uses our 2026 preseason order. H2H uses all 210 regular-season games from 2023–2025.</p></div><div class="grid4 schedule-notables">${card('Hardest road',`${e(roads[0].team)}<br><span class="small">${e(roads[0].manager)} · avg opponent rank ${roads[0].avg.toFixed(2)}</span>`,'SCHEDULE STRENGTH')}${card('Softest road',`${e(roads[roads.length-1].team)}<br><span class="small">${e(roads[roads.length-1].manager)} · avg opponent rank ${roads[roads.length-1].avg.toFixed(2)}</span>`,'SCHEDULE STRENGTH')}${card('Most familiar matchup',`${e(familiar.a)} vs ${e(familiar.b)}<br><span class="small">${e(familiar.ma)} ${reg(familiar.ma,familiar.mb).w}-${reg(familiar.ma,familiar.mb).l} ${e(familiar.mb)} · ${reg(familiar.ma,familiar.mb).total} prior regular-season meetings</span>`,'HISTORY')}${card('Week 1 heavyweight',`${e(wk1.a)} vs ${e(wk1.b)}<br><span class="small">Preseason #${rank[wk1.a]} vs #${rank[wk1.b]}</span>`,'OPENING WEEK')}</div>${closest?`<div class="notice"><b>Closest established series:</b> ${e(closest.ma)} ${reg(closest.ma,closest.mb).w}-${reg(closest.ma,closest.mb).l} ${e(closest.mb)} across ${reg(closest.ma,closest.mb).total} regular-season meetings.</div>`:''}</div></section>`+sec('Marquee dates',`<div class="marquee-list">${marquee||'<div class="empty-state">No tagged marquee games.</div>'}</div>`,'Final rematches, top-four collisions, true rivalries and second meetings are highlighted.','CIRCLE THESE')+`<section class="section alt"><div class="shell"><div class="section-head"><div><p class="eyebrow dark">TEAM-BY-TEAM</p><h2>Every road to Week 14</h2></div><p class="section-intro">Every opponent card includes regular-season H2H and the most recent meeting from the complete archive.</p></div><div class="schedule-team-grid">${teamCards}</div></div></section>`+sec('Full 14-week slate',`<div class="schedule-week-grid">${weekly}</div>`,'Every matchup in one scan, with historical series and marquee tags.','MASTER SCHEDULE')
}
const routes={home,franchises,franchise,transactions,waivers,power,odds,records,weeks,week,history,warroom,h2h,schedule,seasonArchive,trophies};
const currentPage=document.body.dataset.page;
document.body.innerHTML=nav()+(routes[currentPage]||home)()+foot();
if(currentPage==='waivers'){refreshWaivers();const cfg=window.MEFFL_API||{};if(cfg.waiverEndpoint)setInterval(refreshWaivers,Math.max(60,cfg.refreshSeconds||120)*1000)}
